"""
HSA chatbot content: 23 topic nodes from QA_ARCHITECTURE_FROM_KB.md.
Generated by scripts/build_content_from_architecture.py — re-run that script after editing the architecture doc.
"""
from __future__ import annotations
from dataclasses import dataclass
from typing import Optional

@dataclass
class Topic:
    id: str
    label: str
    answer: str
    citations: list[str]
    suggested_questions: list[str]
    next_suggested_topics: list[str]

TOPICS: list[Topic] = [
    Topic(
        id="what_is_hsa",
        label='What is an HSA?',
        answer='A Health Savings Account (HSA) is a special savings account where you\nset money aside — before taxes — to pay for healthcare expenses. The\nsimplest way to think about it: it\'s like a 401(k), but for healthcare\ninstead of retirement.\n\nYou and your employer can both contribute to your HSA, and you use\nthose funds tax-free to pay for a wide range of qualified medical\nexpenses — doctor visits, prescriptions, dental work, vision care,\nmental health therapy, and much more. You decide what to spend, what\nto save, and how to invest it.\n\nThe biggest thing that separates an HSA from other health accounts:\nthe money never expires. There is no "use it or lose it" rule. Your\nbalance rolls over every single year and keeps growing — whether you\nneed it next month or in retirement decades from now.',
        citations=['HealthEquity HSA Guidebook, p. 25', 'HSAs For Dummies, Optum Financial Special Edition, Introduction, p. 1', 'WageWorks Guide to HSAs, p. 8'],
        suggested_questions=['What is an HSA?', "What's an HSA?", 'Explain HSA to me', 'What does HSA stand for?', "I've never heard of an HSA", 'What is a health savings account?'],
        next_suggested_topics=['triple_tax', 'eligibility', 'portability'],
    ),
    Topic(
        id="triple_tax",
        label='What is the triple tax advantage?',
        answer='**Save more on taxes.** The HSA\'s "triple tax advantage" is what makes it the most powerful\nsavings vehicle in the U.S. tax code. No other account gives you all\nthree of these benefits at once.\n\nBenefit 1 — Contributions go in tax-free. Whether you, your employer,\nor a family member contributes, you pay no federal income tax on those\ndollars. If contributions come through payroll, you also skip Social\nSecurity and Medicare taxes (FICA) — a bonus that 401(k)s do not\noffer. For someone in the 22% tax bracket, the effective savings on\na payroll HSA contribution can exceed 30%.\n\nBenefit 2 — Your money grows tax-free. Any interest or investment\nearnings in your HSA accumulate without being taxed year by year, as\nlong as you use the money for qualified medical expenses.\n\nBenefit 3 — Withdrawals are tax-free. When you spend HSA funds on\nqualified medical expenses, you owe zero federal tax — at any age,\nat any time.\n\nOnly 6% of working Americans aged 18 to 34 can correctly identify all\nthree of these benefits. Knowing this puts you well ahead of your peers.',
        citations=['HealthEquity HSA Guidebook, Introduction, p. 5', 'HealthEquity HSA Guidebook, pp. 25–26', 'WageWorks Guide to HSAs, p. 15', 'Generational HSA Divide research document'],
        suggested_questions=['What is the triple tax advantage?', 'How does an HSA save me money on taxes?', 'Is an HSA tax-free?', 'What are the tax benefits of an HSA?', 'Why is an HSA better than other accounts?', 'How do HSA taxes work?'],
        next_suggested_topics=['eligibility', 'contribution_limits', 'hsa_vs_other'],
    ),
    Topic(
        id="eligibility",
        label='Am I eligible?',
        answer="To be eligible to open and contribute to an HSA, three main IRS rules\napply.\n\nRule 1: You must be enrolled in an HSA-qualified health plan —\ncommonly called a High-Deductible Health Plan (HDHP). These plans\ngenerally have lower monthly premiums but higher deductibles. They can\nbe employer-sponsored or purchased through an ACA exchange (bronze and\ncatastrophic level plans often qualify).\n\nRule 2: You cannot have certain other coverage. Specifically, you\ncannot have a standard Health FSA through your employer, be enrolled\nin Medicare, or be claimed as a dependent on someone else's tax return\nfor HSA contribution purposes.\n\nRule 3: No other disqualifying health coverage. If you have access to\na spouse's plan or supplemental coverage that pays expenses before\nyour HDHP deductible is met, that may disqualify you — check with\nyour HR or plan provider.\n\nIf you are currently on a parent's plan, whether you can open an HSA\ndepends on whether that specific plan is HSA-qualified. Once you are\nno longer eligible, you stop contributing — but all existing funds\nremain yours to use on qualified expenses indefinitely.",
        citations=['HealthEquity HSA Guidebook, pp. 6–7', 'WageWorks Guide to HSAs, p. 8'],
        suggested_questions=['Am I eligible for an HSA?', 'Who can open an HSA?', 'Can I have an HSA?', 'Do I qualify for an HSA?', 'What do I need to open an HSA?', "Can I get an HSA on my parent's plan?"],
        next_suggested_topics=['hdhp_basics', 'contribution_limits', 'misconceptions'],
    ),
    Topic(
        id="hdhp_basics",
        label='What is an HDHP?',
        answer='An HSA-qualified health plan — often called a High-Deductible Health\nPlan (HDHP) — is insurance that typically comes with lower monthly\npremiums than traditional plans, but a higher deductible (the amount\nyou pay out-of-pocket before insurance starts covering costs).\n\nThe government sets specific minimum deductible thresholds and maximum\nout-of-pocket limits that a plan must meet to be HSA-eligible. These\nnumbers adjust slightly each year. Your HR department or insurance\nprovider can confirm whether your specific plan qualifies.\n\nA common worry is losing your doctor. In most cases, HSA-qualified\nplans use the same healthcare networks as traditional coverage.\nWhether you stay in-network or use an out-of-network provider, you\ncan pay whatever you owe directly from your HSA.\n\nChoosing an HSA-qualified plan may change how you think about\nhealthcare spending — but it does not mean compromising the quality\nof care you receive.',
        citations=['HealthEquity HSA Guidebook, pp. 6, 8', 'WageWorks Guide to HSAs, p. 15'],
        suggested_questions=['What is a high-deductible health plan?', 'What is an HDHP?', 'What kind of health plan do I need for an HSA?', 'Does my health plan qualify for an HSA?', "What's the difference between an HDHP and regular insurance?"],
        next_suggested_topics=['eligibility', 'contribution_limits', 'qualified_expenses'],
    ),
    Topic(
        id="qualified_expenses",
        label='What can I spend it on?',
        answer="HSA funds can be used for a very wide range of qualified medical\nexpenses — far more than most people realize. The IRS defines a\nqualified medical expense as money paid primarily to prevent or treat\na physical or mental illness.\n\nQualified expenses include: doctor and specialist visits, copays and\ncoinsurance, hospital stays, prescription drugs, dental care, vision\ncare, mental health therapy, hearing aids, and many over-the-counter\n(OTC) products and medications. You can also use HSA funds for your\nspouse and tax dependents, even if they are not on your health plan.\n\nItems that do NOT qualify include general wellness purchases like\nvitamins (unless prescribed for a specific diagnosed condition), gym\nmemberships, or cosmetic-only procedures like teeth whitening.\n\nExplore the sub-topics below to learn what's covered in specific\ncategories.",
        citations=['HSAs For Dummies, Optum Financial Special Edition, p. 24', 'HealthEquity HSA Guidebook, p. 183', 'WageWorks Guide to HSAs, p. 67', 'HSAs For Dummies, Optum Financial Special Edition, p. 27'],
        suggested_questions=['What can I use my HSA for?', 'What are qualified medical expenses?', 'What can I spend HSA money on?', 'Can I use my HSA for prescriptions?', 'What counts as a medical expense for HSA?', 'Can I use my HSA for dental?'],
        next_suggested_topics=['qualified_expenses_mental_health', 'qualified_expenses_dental_vision', 'qualified_expenses_otc', 'qualified_expenses_premiums', 'qualified_expenses_family'],
    ),
    Topic(
        id="qualified_expenses_mental_health",
        label='Mental health & therapy',
        answer="Yes — mental health services are qualified medical expenses. Therapy\nsessions, psychiatric care, counseling, and prescription medications\nfor mental health conditions can all be paid with HSA funds tax-free.\n\nThis is a point many young adults miss. Gen Z and Millennials report\nhigh utilization of behavioral and mental health services — yet 46%\nof Gen Z respondents in one study said they would cut mental health\nspending first if their budget tightened. Using an HSA to cover these\ncosts means you're paying with pre-tax dollars, effectively getting\na 22–30% discount (depending on your tax bracket) on care you may\nalready be accessing.\n\nWhen younger adults understand that HSAs cover mental health therapy\nalongside physical healthcare, their engagement with HSAs increases\nsignificantly.",
        citations=['HSAs For Dummies, Optum Financial Special Edition, p. 24', 'Generational HSA Divide research document'],
        suggested_questions=['Can I use my HSA for therapy?', 'Does HSA cover mental health?', 'Can I pay for counseling with my HSA?', 'Is therapy an eligible HSA expense?', 'Can I use my HSA for a psychiatrist?'],
        next_suggested_topics=['qualified_expenses_otc', 'triple_tax', 'young_adults'],
    ),
    Topic(
        id="qualified_expenses_dental_vision",
        label='Dental & vision',
        answer='Both dental and vision care are covered HSA expenses — which catches\nmany people by surprise, since most health insurance plans do not\ncover them.\n\nDental: Checkups, cleanings, fillings, extractions, braces,\northodontia, implants, and dentures are all qualified. The exception:\npurely cosmetic procedures like teeth whitening are not eligible.\n\nVision: Eye exams, prescription glasses (including frames and\nlenses), contact lenses, contact lens solution, prescription\nsunglasses, and laser eye surgery (such as LASIK or PRK) are all\neligible. OTC reading glasses count too.\n\nSince dental and vision costs are often predictable, some people pair\na Limited Purpose FSA (LPFSA) alongside their HSA specifically to\ncover these expenses — allowing HSA funds to stay invested and\ngrowing for larger future needs.',
        citations=['WageWorks Guide to HSAs, p. 67', 'HSAs For Dummies, Optum Financial Special Edition, p. 27', 'HealthEquity HSA Guidebook, p. 53'],
        suggested_questions=['Can I use my HSA for dental?', 'Does HSA cover glasses or contacts?', 'Can I pay for LASIK with my HSA?', 'Is orthodontia covered by HSA?', 'Can HSA pay for an eye exam?'],
        next_suggested_topics=['qualified_expenses_otc', 'qualified_expenses_premiums', 'complementary_accounts'],
    ),
    Topic(
        id="qualified_expenses_otc",
        label='OTC products & prescriptions',
        answer='Since 2020, a wide range of over-the-counter (OTC) medications and\nproducts became HSA-eligible without needing a prescription — thanks\nto the CARES Act.\n\nEligible OTC items include: allergy medications, pain relievers (like\nTylenol and Advil), cold and flu treatments, cough syrup, sleep aids,\nstomach remedies, anti-fungal and anti-itch treatments, first-aid\nsupplies (bandages, hydrogen peroxide, alcohol wipes), contact lens\nsolution, sunscreen with SPF 15 or above, and menstrual care products\n(pads, tampons, cups, liners, etc.).\n\nPrescription drugs also qualify — generic or brand-name. If you take\nan expensive medication, ask about generic alternatives or check\nwhether the manufacturer offers a discount program.\n\nNote: General toiletries like soap and shampoo do not qualify. Vitamins\nare only eligible if specifically prescribed to treat a diagnosed\ncondition (and a letter of medical necessity from your provider may\nbe required).',
        citations=['HealthEquity HSA Guidebook, p. 101', 'HSAs For Dummies, Optum Financial Special Edition, pp. 25–26'],
        suggested_questions=['Can I buy OTC medicine with my HSA?', 'Does HSA cover Tylenol or Advil?', 'Can I use my HSA for sunscreen?', 'What over-the-counter items are HSA eligible?', 'Are menstrual products covered by an HSA?', 'Can I buy bandages with my HSA?'],
        next_suggested_topics=['qualified_expenses_dental_vision', 'recordkeeping'],
    ),
    Topic(
        id="qualified_expenses_premiums",
        label='Insurance premiums (exceptions)',
        answer="Generally, you cannot use HSA funds to pay health insurance premiums.\nBut there are important exceptions that can be a real lifeline.\n\nPremiums you CAN pay with your HSA:\n- COBRA continuation coverage after leaving a job\n- Health coverage while receiving federal or state unemployment\n  compensation\n- Qualified long-term care insurance (subject to age-based IRS limits)\n- Medicare Parts A, B, C, and D premiums — but only once you turn 65\n- Retiree health plan premiums (but NOT Medigap/Medicare supplement\n  policies)\n\nIf you lose your job, your HSA can cover COBRA premiums tax-free\nwhile you figure out your next coverage step. This safety net is\nsomething most young adults don't know exists until they need it.",
        citations=['HealthEquity HSA Guidebook, pp. 183–184', 'HSAs For Dummies, Optum Financial Special Edition, p. 26', 'WageWorks Guide to HSAs, p. 67'],
        suggested_questions=['Can I use my HSA to pay insurance premiums?', 'Can I pay COBRA with my HSA?', 'Can my HSA pay for Medicare premiums?', 'Can I pay for long-term care with my HSA?', 'What insurance can I pay with my HSA?'],
        next_suggested_topics=['age_65_medicare', 'portability', 'qualified_expenses'],
    ),
    Topic(
        id="qualified_expenses_family",
        label='Paying for family members',
        answer="Yes — you can use your HSA to pay qualified medical expenses for your\nspouse and any tax dependents, even if they are not enrolled in your\nHSA-qualified health plan.\n\nA dependent is generally someone you can claim on your tax return:\nchildren, stepchildren, and in some cases other qualifying relatives.\nIn divorce situations, either parent can use their own HSA to pay a\nchild's qualified expenses — even if only one parent claims the child\nas a tax dependent.\n\nThe same rules that define eligible expenses for you apply equally\nto your covered family members. You get the same tax-free benefit\nregardless of whose name is on the medical bill.",
        citations=['HSAs For Dummies, Optum Financial Special Edition, p. 27'],
        suggested_questions=['Can I use my HSA for my spouse?', 'Can I use my HSA for my kids?', "Can I pay for my family's medical bills with my HSA?", 'Does HSA cover dependents?', "Can I use HSA for my partner's expenses?"],
        next_suggested_topics=['contribution_limits', 'qualified_expenses'],
    ),
    Topic(
        id="contribution_limits",
        label='Contribution limits',
        answer='The IRS sets annual limits on how much can go into your HSA — from\nall sources combined (you, your employer, family members, anyone).\nThese limits adjust each year based on inflation.\n\nFor 2025, the limits are:\n- Self-only coverage: $4,300\n- Family coverage: $8,750\n- Catch-up contribution if you are 55 or older: an extra $1,000\n\nNo matter who contributes, the combined total from all sources cannot\nexceed the annual limit. Only your own contributions and your\nemployer\'s contributions receive the direct tax benefit at the time\nof contribution. Contributions from others (like family members) can\nbe claimed as an above-the-line deduction on your tax return.\n\nIf you exceed the limit — even because of an employer contribution —\nyou will owe a 6% excise tax on the excess. If you open your HSA\nmid-year, you can still contribute the full year\'s maximum using the\n"last-month rule," but you must remain eligible through the end of\nthe following year or face taxes and a 10% penalty on any overage.',
        citations=['HealthEquity HSA Guidebook, p. 38', 'HealthEquity HSA Guidebook, pp. 77–79, 96', 'HSAs For Dummies, Optum Financial Special Edition, p. 13'],
        suggested_questions=['How much can I put in my HSA?', 'What are the HSA contribution limits?', 'Is there a max for HSA contributions?', 'How much can I contribute to an HSA per year?', 'Can my employer also contribute to my HSA?', 'What happens if I contribute too much to my HSA?'],
        next_suggested_topics=['funding_strategy', 'investment', 'triple_tax'],
    ),
    Topic(
        id="investment",
        label='Investing my HSA',
        answer='Yes — and this is the most underused HSA feature. You can invest your\nHSA balance in stocks, bonds, mutual funds, and certificates of\ndeposit, similar to an IRA or 401(k). Your investment earnings grow\nentirely tax-free.\n\nMost HSA administrators allow investing once your cash balance reaches\na minimum threshold — typically $1,000 to $2,000. Any amount above\nthat threshold can be moved into investment options. If you need funds\nfor a medical expense, you can move money back to cash at any time\nwith no tax penalty.\n\nThe math is compelling: saving $3,000 per year for 30 years without\ninvesting accumulates to about $90,000. Invested at a 7% average\nannual return, that same $3,000 per year grows to approximately\n$306,000 — over $200,000 more, all tax-free for qualified expenses.\n\nDespite this potential, only 9–15% of HSA holders invest their funds;\nmost accounts sit in cash. If you can afford to pay current medical\nexpenses out of pocket, letting your HSA balance grow invested is one\nof the most powerful financial moves available to young adults.',
        citations=['HealthEquity HSA Guidebook, pp. 66, 127–129', 'HSAs For Dummies, Optum Financial Special Edition, p. 20', 'WageWorks Guide to HSAs, p. 64', 'Behavioral Architecture of Financial Avoidance research document'],
        suggested_questions=['Can I invest my HSA?', 'How do I invest my HSA money?', 'Does my HSA earn interest?', 'Can my HSA grow like a retirement account?', 'What investment options does an HSA have?', 'Should I invest my HSA?'],
        next_suggested_topics=['hsa_vs_other', 'funding_strategy', 'retirement_planning'],
    ),
    Topic(
        id="hsa_vs_other",
        label='HSA vs 401(k), FSA & IRA',
        answer='The HSA is the only account in the U.S. that combines all three tax\nbenefits: tax-free contributions, tax-free growth, and tax-free\nwithdrawals for qualified expenses. Every other account offers only\none or two of those.\n\nHSA vs 401(k): Both allow pre-tax contributions. But 401(k)\nwithdrawals are taxed as income in retirement. HSA withdrawals for\nqualified medical expenses are never taxed. Additionally, HSA\npayroll contributions skip FICA taxes (Social Security and Medicare)\n— a benefit 401(k) contributions do not get.\n\nHSA vs Traditional IRA: IRAs reduce your taxable income now but are\ntaxed on withdrawal. HSA withdrawals for qualified expenses are tax-\nfree at any time. High earners may also lose IRA deductibility above\ncertain income thresholds — HSAs have no income limit.\n\nHSA vs FSA: The FSA\'s critical drawback is the "use it or lose it"\nrule — unspent FSA funds generally expire at year-end. HSA funds\nroll over indefinitely. Confusing these two accounts is one of the\nmost common barriers to HSA adoption among young adults.',
        citations=['HealthEquity HSA Guidebook, pp. 5–6, 29', 'WageWorks Guide to HSAs, p. 15', 'Behavioral Architecture of Financial Avoidance research document'],
        suggested_questions=['How is an HSA different from a 401k?', "What's the difference between HSA and FSA?", 'HSA vs FSA — which is better?', 'How does an HSA compare to an IRA?', 'Is an HSA better than a 401k?', 'Should I choose an HSA or an FSA?'],
        next_suggested_topics=['triple_tax', 'complementary_accounts', 'misconceptions'],
    ),
    Topic(
        id="portability",
        label="It's yours — forever",
        answer='Your HSA belongs to you — not your employer, not your insurance\ncompany. It stays with you when you change jobs, change health plans,\nmove, or get married. Think of it the same way as a 401(k): it\'s\nyours.\n\nYour HSA balance rolls over automatically every year. There is no\ndeadline and no "use it or lose it" pressure. If you don\'t spend the\nmoney this year, it stays in your account and keeps growing.\n\nIf you lose HSA eligibility — for example, by switching to a\nnon-qualifying health plan — you stop being able to make new\ncontributions. But every dollar already in the account remains yours,\nand you can keep spending it on qualified medical expenses for as\nlong as you need.\n\nWhen you pass away, your HSA becomes part of your estate. If your\nspouse is your named beneficiary, they can inherit the account as\ntheir own HSA — tax-free.',
        citations=['HealthEquity HSA Guidebook, p. 6', 'HSAs For Dummies, Optum Financial Special Edition, p. 42', 'WageWorks Guide to HSAs, p. 75'],
        suggested_questions=['What happens to my HSA if I change jobs?', 'Do I lose my HSA if I leave my employer?', 'Is my HSA portable?', 'Who owns my HSA?', "What happens to HSA money I don't use?", 'Does my HSA expire?'],
        next_suggested_topics=['investment', 'age_65_medicare', 'what_is_hsa'],
    ),
    Topic(
        id="funding_strategy",
        label='How should I fund my HSA?',
        answer="A good starting rule: always contribute at least enough to capture any\nemployer match or employer contribution your plan offers. That is free\nmoney — do not leave it on the table.\n\nAfter capturing your employer's contribution, consider contributing up\nto the full IRS annual maximum. Because HSAs offer more tax advantages\nthan 401(k)s — including the FICA exemption on payroll contributions\n— many financial planners suggest maxing your HSA before adding extra\nto a 401(k) beyond any employer match.\n\nIf your budget allows, consider paying current medical expenses out\nof pocket and letting your entire HSA balance grow invested. You can\nreimburse yourself for old expenses at any time — even years later —\nas long as the expense occurred after your HSA was opened. This\nstrategy maximizes your invested balance and compounds your tax-free\ngrowth.\n\nIf money is tight, even small regular contributions add up. HSA funds\nnever expire, and every pre-tax dollar saved reduces your tax bill\nnow and grows your balance for later.",
        citations=['HealthEquity HSA Guidebook, pp. 118–119', 'HealthEquity HSA Guidebook, p. 49'],
        suggested_questions=['How should I contribute to my HSA?', 'Should I max out my HSA?', 'How do I get the most from my HSA?', 'Should I contribute to my HSA or 401k first?', 'How much should I put in my HSA?', 'My employer contributes to my HSA — what should I do?'],
        next_suggested_topics=['investment', 'contribution_limits', 'complementary_accounts'],
    ),
    Topic(
        id="young_adults",
        label='Why does this matter for me?',
        answer='The "I\'m healthy, I don\'t need this" mindset is the most common reason\nyoung adults miss out on one of the best financial tools available to\nthem. Research confirms it: only 6% of working Americans aged 18 to\n34 can correctly describe all three HSA tax benefits.\n\nHere\'s the reframe: being young is actually the best time to open an\nHSA. If you rarely need healthcare, your money just stays in the\naccount and grows — potentially for decades, entirely tax-free. The\nless you spend now, the more you accumulate for later.\n\nAnd young adults use healthcare more than the "invincible" image\nsuggests. Gen Z and Millennials are among the highest users of mental\nhealth and behavioral health services. HSAs cover therapy,\nprescriptions, and many other expenses you might already be paying\nfor out of pocket.\n\nThe most common moment young adults realize HSA value is when they\nage off a parent\'s health plan at 26 — or face a surprise medical\nbill. Starting before either of those moments means you\'ll have a\nfunded account ready when you actually need it.',
        citations=['Generational HSA Divide research document', 'Behavioral Architecture of Financial Avoidance research document', 'HSA Bank Health and Wealth Index research document'],
        suggested_questions=["I'm young and healthy — why do I need an HSA?", 'Why should I care about an HSA?', 'I never go to the doctor. Should I get an HSA?', "What's in it for me as a young person?", "Is an HSA worth it if I don't have many medical expenses?", "I'm just starting out — is an HSA for me?"],
        next_suggested_topics=['qualified_expenses_mental_health', 'triple_tax', 'investment', 'misconceptions'],
    ),
    Topic(
        id="age_65_medicare",
        label='HSA at age 65 & Medicare',
        answer="At age 65, your HSA becomes even more flexible. You can still use it\ntax-free for any qualified medical expense. But you can now also use\nit for non-medical expenses without penalty — you'll just pay ordinary\nincome tax on those withdrawals, the same as a traditional IRA.\n\nOnce you enroll in Medicare, you can no longer make new HSA\ncontributions. But your existing balance remains available. You can\nuse it to pay Medicare premiums for Parts A, B, C (Medicare\nAdvantage), and D (prescription drugs) — as well as copays and\ncoinsurance. The one exception: HSA funds cannot pay for a Medigap\n(Medicare supplement) policy.\n\nIf you delay Medicare past 65 and keep an HSA-qualified health plan,\nyou can keep contributing — including the $1,000 catch-up\ncontribution — for as long as you remain eligible.\n\nFor married couples where both spouses are 55 or older, each can\nmake their own $1,000 catch-up contribution. Each spouse must have\ntheir own separate HSA account for this to work.",
        citations=['HealthEquity HSA Guidebook, pp. 77–78', 'WageWorks Guide to HSAs, p. 75'],
        suggested_questions=['What happens to my HSA when I turn 65?', 'Can I use my HSA in retirement?', 'Does Medicare affect my HSA?', 'Can I use my HSA to pay Medicare premiums?', 'What happens to my HSA when I enroll in Medicare?'],
        next_suggested_topics=['retirement_planning', 'portability', 'investment'],
    ),
    Topic(
        id="retirement_planning",
        label='HSA for retirement',
        answer='Retirement healthcare costs are one of the biggest financial risks\nmost people underestimate. According to the Employee Benefit Research\nInstitute (EBRI), a married couple with average prescription drug\nneeds will need approximately $366,000 to cover out-of-pocket medical\nexpenses in retirement.\n\nAn HSA is uniquely positioned to address this. Unlike a 401(k) or\nIRA, HSA withdrawals for healthcare are never taxed — even in\nretirement. If you invest your HSA contributions throughout your\nworking years, those funds can grow substantially, entirely tax-free.\n\nYoung people just starting their careers have the greatest advantage:\ndecades of tax-free compounding ahead of them. Even modest regular\ncontributions, invested over time, can make a significant difference.\nIt is never too early — or too late — to start.\n\nAfter age 65, HSA funds can also be used penalty-free for non-medical\nexpenses (taxed as ordinary income), giving you a flexible additional\nreserve alongside your 401(k) and Social Security.',
        citations=['HealthEquity HSA Guidebook, pp. 8–9, 118'],
        suggested_questions=['Can I use my HSA for retirement?', 'How does an HSA help with retirement savings?', 'Should I use my HSA as a retirement account?', 'How much will I need for healthcare in retirement?', 'Is an HSA a good long-term savings tool?'],
        next_suggested_topics=['investment', 'age_65_medicare', 'hsa_vs_other'],
    ),
    Topic(
        id="recordkeeping",
        label='Receipts & recordkeeping',
        answer='Treat your HSA records the way you would any financial account —\nsavings, investment, or credit card. Keep documentation showing what\nyou spent and why it was a qualified expense.\n\nAlways save itemized receipts and any Explanation of Benefits (EOB)\nnotices from your health plan. If you paid for a medical expense out\nof pocket and want to reimburse yourself from your HSA later — even\nyears later — those receipts make it possible. There is no IRS\ndeadline on reimbursement, as long as the expense occurred after your\nHSA was opened.\n\nIf the IRS ever questions your HSA withdrawals, your receipts are your\ndefense. Without them, a qualified withdrawal could be treated as\nnon-qualified — triggering income tax plus a 20% penalty.\n\nMost HSA providers have an online portal or app where you can track\ntransactions and store receipts digitally. Build the habit early and\nit takes almost no time.',
        citations=['HSAs For Dummies, Optum Financial Special Edition, p. 20', 'HealthEquity HSA Guidebook, p. 130'],
        suggested_questions=['Do I need to save receipts for my HSA?', 'How do I track my HSA spending?', 'What records do I need to keep for my HSA?', 'Can I get audited on my HSA?', 'How do I reimburse myself from my HSA?'],
        next_suggested_topics=['qualified_expenses', 'contribution_limits'],
    ),
    Topic(
        id="complementary_accounts",
        label='HSA + FSA/HRA together',
        answer='In most cases, having a standard Health FSA or general-purpose HRA\nalongside an HSA will disqualify you from contributing to the HSA.\nHowever, there are HSA-compatible versions designed to work together.\n\nA Limited Purpose FSA (LPFSA) covers only dental and vision expenses.\nBecause it doesn\'t cover general medical expenses, it doesn\'t\ndisqualify your HSA. Using both lets you pay predictable dental and\nvision costs from the LPFSA (with its "use it or lose it" FSA funds)\nwhile keeping your HSA balance invested and growing for everything\nelse.\n\nA Post-Deductible HRA is also compatible — it only reimburses medical\nexpenses after you\'ve met your HDHP\'s minimum deductible, so it\ndoesn\'t interfere with HSA eligibility.\n\nThe strategic advantage: pairing an LPFSA with a maxed-out HSA lets\nyou protect more of your HSA balance for long-term investment, since\ndental and vision costs are covered elsewhere.',
        citations=['WageWorks Guide to HSAs, p. 39', 'HealthEquity HSA Guidebook, pp. 53–54'],
        suggested_questions=['Can I have both an HSA and an FSA?', 'What is a limited purpose FSA?', 'Can my employer give me an HRA if I have an HSA?', 'What is an HSA-compatible FSA?', 'How do I pair my HSA with other benefits?'],
        next_suggested_topics=['hsa_vs_other', 'qualified_expenses_dental_vision', 'funding_strategy'],
    ),
    Topic(
        id="misconceptions",
        label='Common HSA myths',
        answer='HSAs have a reputation for being complicated — but that reputation is\nmostly undeserved. As one guide puts it: "If you can open a savings\naccount, you can handle an HSA."\n\nMyth 1: "It\'s use-it-or-lose-it." False. HSA funds roll over\nindefinitely. There is no deadline to spend the money.\n\nMyth 2: "It\'s only for sick people or big expenses." False. HSAs\ncover everyday costs like prescriptions, OTC medications, therapy,\ndental, and vision — things most people already pay for.\n\nMyth 3: "It\'s the same as an FSA." No. FSAs do have a use-it-or-\nlose-it rule. HSAs are permanent, portable accounts that you own.\n\nMyth 4: "I can\'t invest my HSA." False. Most HSAs let you invest in\nmutual funds, stocks, and more — and those earnings are entirely\ntax-free.\n\nMyth 5: "My employer controls it." False. You own your HSA. Your\nemployer can contribute to it but has no control over how you use it.\n\nDespite these facts, 66% of HSA holders do not know how their funds\nare invested, and over 80% of lower-literacy holders don\'t know if\ntheir balance is in cash or market assets. Knowing even the basics\nputs you ahead of the majority of account holders.',
        citations=['HSAs For Dummies, Optum Financial Special Edition, Introduction, p. 1', 'WageWorks Guide to HSAs, p. 75', 'Behavioral Architecture of Financial Avoidance research document'],
        suggested_questions=['Is an HSA complicated?', "I've heard HSAs are confusing — is that true?", 'What do people get wrong about HSAs?', 'Are there myths about HSAs I should know?', 'I thought I had to spend my HSA money every year'],
        next_suggested_topics=['what_is_hsa', 'young_adults', 'triple_tax'],
    ),
    Topic(
        id="non_qualified_withdrawals",
        label='What if I spend it wrong?',
        answer='If you use HSA funds for a non-qualified expense before age 65, you\nwill owe ordinary income tax on that amount plus a 20% penalty. That\nis steep — so knowing what qualifies matters.\n\nAfter age 65, the 20% penalty disappears. You can use HSA funds for\nany purpose — but non-medical withdrawals are still subject to\nordinary income tax, just like a traditional 401(k).\n\nIf you accidentally use your HSA for a non-qualified expense, some\nHSA administrators will allow you to return the funds before the tax\nfiling deadline without penalty — check with your specific provider.\n\nYou cannot deduct an expense on your taxes and also use HSA funds for\nthe same expense. "Double-dipping" is not permitted by the IRS.',
        citations=['HealthEquity HSA Guidebook, p. 101', 'WageWorks Guide to HSAs, p. 75'],
        suggested_questions=['What happens if I use my HSA for non-medical expenses?', 'What is the penalty for misusing my HSA?', 'Can I withdraw HSA money for anything I want?', "What if I accidentally spend HSA money on something that doesn't qualify?", 'Is there a penalty for wrong HSA withdrawals?'],
        next_suggested_topics=['qualified_expenses', 'age_65_medicare', 'recordkeeping'],
    ),
    Topic(
        id="opening_an_hsa",
        label='How do I open an HSA?',
        answer='You can open an HSA through several channels depending on your\nsituation.\n\nThrough your employer: Most people enroll during open enrollment\nusing their HR or benefits portal. If your employer offers an HSA-\nqualified health plan, they typically have a preferred HSA provider\nalready set up, and contributions can come directly through payroll\n(with FICA tax savings).\n\nOn your own: You can open an HSA independently at a bank, credit\nunion, or HSA-specific administrator. This is common for self-\nemployed individuals or people on marketplace plans. You contribute\nafter-tax dollars and claim the deduction on your federal tax return.\n\nWhen comparing providers, look at: monthly fees and transaction fees,\ninvestment options and minimum balance requirements, ease of access\n(app, online portal), and whether automated investing is available.\nLower fees compound into meaningfully more money over time.\n\nYour HSA custodian will have you complete a trust or custodial\nagreement (IRS Form 5305-B or 5305-C). Most providers allow this\nentirely online.',
        citations=['HealthEquity HSA Guidebook, pp. 62–66'],
        suggested_questions=['How do I open an HSA?', 'Where can I get an HSA?', 'How do I start an HSA?', 'Can I open an HSA on my own?', 'Do I open my HSA through my employer?'],
        next_suggested_topics=['eligibility', 'contribution_limits', 'funding_strategy'],
    ),
]

DEFAULT_WELCOME_TOPIC_IDS = ["what_is_hsa", "young_adults", "triple_tax", "misconceptions", "qualified_expenses"]

# Topic difficulty / pacing tags (visual only — reduces overwhelm, signals natural order).
# 🟢 Good starting point | 🟡 A little more detail | 🔵 When you're ready
TOPIC_DIFFICULTY: dict[str, dict[str, str]] = {
    "what_is_hsa": {"emoji": "🟢", "label": "Good starting point"},
    "portability": {"emoji": "🟢", "label": "Good starting point"},
    "misconceptions": {"emoji": "🟢", "label": "Good starting point"},
    "triple_tax": {"emoji": "🟡", "label": "A little more detail"},
    "qualified_expenses": {"emoji": "🟡", "label": "A little more detail"},
    "contribution_limits": {"emoji": "🟡", "label": "A little more detail"},
    "investment": {"emoji": "🔵", "label": "When you're ready"},
    "retirement_planning": {"emoji": "🔵", "label": "When you're ready"},
    "complementary_accounts": {"emoji": "🔵", "label": "When you're ready"},
}


def get_topic_difficulty(topic_id: str) -> Optional[dict[str, str]]:
    """Return {emoji, label} for a topic's difficulty tag, or None if untagged."""
    return TOPIC_DIFFICULTY.get(topic_id)


def get_topics_by_difficulty_filter(filter_label: Optional[str]) -> list["Topic"]:
    """Return topics. If filter_label is None or 'All', return all; else only topics with that difficulty label."""
    if not filter_label or filter_label == "All":
        return list(TOPICS)
    return [t for t in TOPICS if get_topic_difficulty(t.id) and get_topic_difficulty(t.id)["label"] == filter_label]


QUALIFIED_EXPENSES_SUB_TOPIC_IDS = [
    "qualified_expenses_mental_health",
    "qualified_expenses_dental_vision",
    "qualified_expenses_otc",
    "qualified_expenses_premiums",
    "qualified_expenses_family",
]
SUGGESTED_TOPIC_LABELS = [t.label for t in TOPICS]

def get_topic_by_id(topic_id: str) -> Optional[Topic]:
    for t in TOPICS:
        if t.id == topic_id:
            return t
    return None

def get_topic_by_label(label: str) -> Optional[Topic]:
    label_clean = label.strip()
    for t in TOPICS:
        if t.label.strip() == label_clean:
            return t
    return None

def get_topic_by_suggested_question(user_message: str) -> Optional[Topic]:
    msg = user_message.strip().lower()
    if not msg:
        return None
    for t in TOPICS:
        for q in t.suggested_questions:
            if q.strip().lower() == msg:
                return t
            if q.strip().lower() in msg or msg in q.strip().lower():
                return t
    return None

def get_all_topics() -> list[Topic]:
    return list(TOPICS)

def get_welcome_topics() -> list[Topic]:
    return [t for t in TOPICS if t.id in DEFAULT_WELCOME_TOPIC_IDS]


def get_qualified_expenses_sub_topics() -> list[Topic]:
    """Sub-topics to show after the main qualified_expenses answer (hub)."""
    return [t for t in TOPICS if t.id in QUALIFIED_EXPENSES_SUB_TOPIC_IDS]
